# Generated by Django 4.2 on 2023-06-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_chat_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="message",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
